name: Test

on:
  push:
    branches:
      - MusicalNinjaDad/issue1850*

jobs:
  lint:
    name: Linters (mypy, flake8, etc.)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - uses: pre-commit/action@v3.0.1
    - name: Check manifest
      run: pipx run nox -s check_manifest
    - name: PyLint checks
      run: pipx run nox -s pylint -- --output-format=github

  test:
    name: Test on ${{ matrix.os }} (${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-14]
        python_version: ['3.12']
    timeout-minutes: 180
    steps:

    - name: Clone FizzBuzz at offending SHA
      uses: actions/checkout@v4
      with:
        repository: 'MusicalNinjaDad/FizzBuzz'
        ref: 'pr48'
        path: '.'

    - uses: actions/checkout@v4
      with:
        path: 'cibw'

    - uses: actions/setup-python@v5
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - name: Show resulting directories
      shell: bash
      run: |
        pwd
        ls -al

    - name: Run a sample build (GitHub Action)
      uses: ./cibw/
      env:
        CIBW_BEFORE_TEST_MACOS: 'ls -al && echo {package} && ls -al {package}'
        CIBW_BEFORE_TEST_WINDOWS: 'ls && echo {package} && ls {package}'
